### ISSUE TITLE
Could not find Terminal::ANSIColor

### ISSUE THREAD

**Issue by jabowery** [tony-o/perl6-data-dump#21] opened 2016-12-30 01:49 UTC
This error occurs whether or not I include the `, :color(False)`.
```
| Dump($matchobject, :color(False));
> 
+ Exception Thrown
| Could not find Terminal::ANSIColor in:
|     /home/jabowery/dev/planner/lib
|     /home/jabowery/.perl6
|     /home/jabowery/.rakudobrew/moar-nom/install/share/perl6/site
|     /home/jabowery/.rakudobrew/moar-nom/install/share/perl6/vendor
|     /home/jabowery/.rakudobrew/moar-nom/install/share/perl6
|     CompUnit::Repository::AbsolutePath<72730608>
|     CompUnit::Repository::NQP<69026008>
|     CompUnit::Repository::Perl5<69026048>

```
It also occurs before and after:
```
$ panda uninstall Terminal::ANSIColor
$ panda install Terminal::ANSIColor
```

**Comment by tony-o** [comment] 2017-01-07 17:40
@jabowery what is the output of `perl6 -v`?

**Comment by tony-o** [comment] 2017-02-07 03:33
I cannot reproduce this error on current rakudo, please reopen if you feel this was closed in error.

**Closed as completed by tony-o** 2017-02-07 03:33 UTC
